name: Pull request labeler
on: 
  schedule:
    - cron: '30 5 * * 1,3'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch: 
jobs:
  triage:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: actions/labeler@v4
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
